require('settings')
require('plugins').setup()
require('keymaps')
require('utils')
require('config.telescope')
-- require('lsp')
-- require("neodev").setup({})
-- require('config.lsp-lua').setup()
require('config/lifetrak').setup()
require('config/hupoon').setup()

