require('settings')
require('plugins').setup()
require('keymaps')
require('reload')
require('hupoon')
require('lsp')
require("neodev").setup({})
require('config.telescope')
require('config.lsp-lua').setup()

